import Head from 'next/head'
import PizzaList from '../components/PizzaList';
import Featured from '../components/Featured';

export default function Home({pizzaList}) {
  
  return (
    <div >
      <Head>
        <title>Pizza Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <Featured/>
      <PizzaList pizzaList={pizzaList}/>
      
    </div>
  )
}

export const getServerSideProps = async() =>{
  
    const res = await fetch("http://localhost:3000/api/orders/products");
    const data = await res.json()
  
 
  return{
    props:{
      pizzaList:data,
    }
  }
}
